from django.core.management.base import BaseCommand
from api.models import Product

PRODUCTS_DATA = [
    # ------------------- SHIRTS -------------------
    {
        "name": "Cotton Shirt Solid Brown",
        "description": "Crafted from 100% breathable pure cotton, this solid brown shirt offers timeless casual elegance and all-day comfort.",
        "price": 1999,
        "image": "https://i.pinimg.com/736x/1a/81/12/1a8112a55105cf0a636eea0f16bee1d4.jpg",
        "category": "shirts",
        "stock": 25,
    },
    {
        "name": "Casual Shirt Solid Olive",
        "description": "Modern olive green casual shirt with a relaxed tailored silhouette. Perfect for everyday layering.",
        "price": 1499,
        "image": "https://i.pinimg.com/736x/d0/09/d7/d009d7a37718acd9a07df8118a24e095.jpg",
        "category": "shirts",
        "stock": 20,
    },
    {
        "name": "Casual Shirt Solid Navy Blue",
        "description": "Deep navy blue shirt designed with premium twill cotton for a versatile day-to-night look.",
        "price": 1799,
        "image": "https://i.pinimg.com/736x/e3/f9/4b/e3f94bf4c5db8afb00855d8998fe425e.jpg",
        "category": "shirts",
        "stock": 30,
    },
    {
        "name": "Casual Shirt Solid Red",
        "description": "Bold red casual shirt featuring clean stitching, pointed collar, and comfortable regular fit.",
        "price": 1899,
        "image": "https://i.pinimg.com/736x/8a/44/0e/8a440ee1e291f91822c1583dfa21cf05.jpg",
        "category": "shirts",
        "stock": 15,
    },
    {
        "name": "Casual Shirt Sky Blue",
        "description": "Crisp sky blue shirt tailored from lightweight cotton blend, suitable for work and weekend outings.",
        "price": 2199,
        "image": "https://i.pinimg.com/736x/01/4d/3d/014d3dddbcd0227a33db85c1e3326aa5.jpg",
        "category": "shirts",
        "stock": 18,
    },
    {
        "name": "Casual Shirt Pink",
        "description": "Subtle pastel pink shirt offering a sophisticated pop of color to your modern wardrobe.",
        "price": 1699,
        "image": "https://i.pinimg.com/736x/91/ab/ff/91abff19fb85fb5e677d59912cf61c17.jpg",
        "category": "shirts",
        "stock": 22,
    },
    {
        "name": "Casual Shirt Solid Black",
        "description": "Sleek all-black button-down shirt with a minimalist finish and ultra-smooth handfeel.",
        "price": 1499,
        "image": "https://i.pinimg.com/1200x/97/a0/bc/97a0bccebc5e4f55edc8ea59617ad531.jpg",
        "category": "shirts",
        "stock": 35,
    },
    {
        "name": "Casual Shirt White",
        "description": "The quintessential classic white shirt with crisp modern tailoring and durable mother-of-pearl buttons.",
        "price": 1599,
        "image": "https://i.pinimg.com/736x/fb/0d/72/fb0d7225ee444c56cdd40d4b6b8224f1.jpg",
        "category": "shirts",
        "stock": 40,
    },
    {
        "name": "Oversized Streetwear Shirt",
        "description": "Trendy oversized cut with dropped shoulders for effortless urban streetwear aesthetics.",
        "price": 1499,
        "image": "https://i.pinimg.com/1200x/17/a4/2b/17a42be4e61185ac9eb3660de77f23ee.jpg",
        "category": "shirts",
        "stock": 15,
    },
    {
        "name": "Vintage Wash Shirt",
        "description": "Distressed vintage-washed fabric for a rugged, timeless heritage appeal with soft texture.",
        "price": 3299,
        "image": "https://i.pinimg.com/1200x/c1/12/a6/c112a692946eff580272a1cd6e6be6c6.jpg",
        "category": "shirts",
        "stock": 12,
    },
    {
        "name": "Khaki Utility Shirt",
        "description": "Functional military-inspired utility shirt with dual chest pockets and reinforced stitching.",
        "price": 1349,
        "image": "https://i.pinimg.com/736x/00/d0/5f/00d05fb58beb757200516aa6ccc4dad6.jpg",
        "category": "shirts",
        "stock": 25,
    },
    {
        "name": "Flannel Checked Shirt",
        "description": "Warm and cozy brushed cotton flannel shirt in classic plaid patterns for cooler days.",
        "price": 1239,
        "image": "https://i.pinimg.com/736x/3b/ae/7d/3bae7d59abffbf23ea0ed2ba437e6aea.jpg",
        "category": "shirts",
        "stock": 18,
    },
    {
        "name": "Resort Cuban Collar Shirt",
        "description": "Breezy Cuban camp collar shirt designed for beach vacations, summer parties, and warm evenings.",
        "price": 3239,
        "image": "https://i.pinimg.com/1200x/68/19/35/6819350816a82a3e9a65c197f1b02d56.jpg",
        "category": "shirts",
        "stock": 14,
    },
    {
        "name": "Textured Knit Shirt",
        "description": "Luxurious open-weave textured knit shirt blending vintage retro flair with modern luxury.",
        "price": 4229,
        "image": "https://i.pinimg.com/1200x/77/84/12/778412e1ad6dbc2db1272f0b9db9e4f9.jpg",
        "category": "shirts",
        "stock": 10,
    },
    {
        "name": "Lightweight Beach Shirt",
        "description": "Ultra-lightweight breathable linen blend crafted to keep you cool under the sun.",
        "price": 1429,
        "image": "https://i.pinimg.com/1200x/6a/72/6b/6a726be39a6e33e7edc842b562a1c66d.jpg",
        "category": "shirts",
        "stock": 20,
    },
    {
        "name": "Denim Button-Up Shirt",
        "description": "Durable washed denim shirt with western yoke detailing and snap button closures.",
        "price": 1419,
        "image": "https://i.pinimg.com/736x/7b/6a/70/7b6a70ff0cefc393e40487f7bcb5d5af.jpg",
        "category": "shirts",
        "stock": 16,
    },
    {
        "name": "Relaxed Fit Shirt",
        "description": "Contemporary relaxed drape with soft fluid fabric for an understated modern look.",
        "price": 1442,
        "image": "https://i.pinimg.com/1200x/ac/45/af/ac45af29ef818e8d06716138f5c36212.jpg",
        "category": "shirts",
        "stock": 22,
    },
    {
        "name": "Check Shirt",
        "description": "Smart casual check pattern shirt with tailored cuffs and spread collar.",
        "price": 1659,
        "image": "https://i.pinimg.com/1200x/27/c9/e1/27c9e10b7416d75f2c6706f73496dba1.jpg",
        "category": "shirts",
        "stock": 28,
    },
    {
        "name": "Knitted Shirt",
        "description": "Fine gauge knit shirt offering stretch, comfort, and sophisticated structure.",
        "price": 1549,
        "image": "https://i.pinimg.com/736x/2e/f9/ad/2ef9adff69cfb74f407d42b2ea725255.jpg",
        "category": "shirts",
        "stock": 15,
    },
    {
        "name": "Street Wear Overshirt",
        "description": "Heavyweight cotton twill overshirt ideal for layering over tees and hoodies.",
        "price": 1412,
        "image": "https://i.pinimg.com/736x/60/86/d9/6086d9a1d72a7da6c93aafe0b3cfe763.jpg",
        "category": "shirts",
        "stock": 19,
    },

    # ------------------- PANTS -------------------
    {
        "name": "Relaxed-Fit Pants",
        "description": "Comfortable relaxed-fit trousers made from breathable cotton twill with an elasticated waistband.",
        "price": 1199,
        "image": "https://i.pinimg.com/736x/e6/a4/77/e6a477a6b4980c2db2f432abc8d3f4e1.jpg",
        "category": "pants",
        "stock": 25,
    },
    {
        "name": "Cargo-Fit Trousers",
        "description": "Functional cargo pants with multiple utility pockets, drawstring hem, and durable ripstop fabric.",
        "price": 1299,
        "image": "https://i.pinimg.com/736x/43/ee/ad/43eead082671f646c2deaafc886580b2.jpg",
        "category": "pants",
        "stock": 30,
    },
    {
        "name": "Loose-Fit Pleated Trousers",
        "description": "Premium wide loose-fit trousers with front pleats, ideal for a refined smart-casual aesthetic.",
        "price": 2799,
        "image": "https://i.pinimg.com/736x/9c/a7/9b/9ca79b83ff75eebb94bdab4ac63f676c.jpg",
        "category": "pants",
        "stock": 15,
    },
    {
        "name": "Classic Denim Jeans",
        "description": "Durable regular-fit denim jeans with 5-pocket styling and vintage stone-washed finish.",
        "price": 1499,
        "image": "https://i.pinimg.com/1200x/ea/76/a2/ea76a24f1f7a5e5db8387982fbf4c001.jpg",
        "category": "pants",
        "stock": 35,
    },
    {
        "name": "Bell-Bottom Jeans 26",
        "description": "Retro flare bell-bottom jeans designed with premium stretch denim for a flattering fit.",
        "price": 1399,
        "image": "https://i.pinimg.com/736x/d0/58/28/d05828d652b80aa67c540c2609534d5a.jpg",
        "category": "pants",
        "stock": 20,
    },
    {
        "name": "Street-Wear Fit Pants",
        "description": "Urban baggy-fit trousers tailored for effortless street fashion and maximum mobility.",
        "price": 1399,
        "image": "https://i.pinimg.com/736x/7a/21/89/7a21897685db90272873dd905c260f53.jpg",
        "category": "pants",
        "stock": 22,
    },
    {
        "name": "Bell-Bottom Jeans 24",
        "description": "Vintage bootcut flared jeans in washed charcoal black with reinforced seams.",
        "price": 1599,
        "image": "https://i.pinimg.com/736x/51/c9/9a/51c99ad8899d65d0a5c6bb4793c65a55.jpg",
        "category": "pants",
        "stock": 18,
    },
    {
        "name": "Tailored Casual Fit Grey",
        "description": "Sleek grey tailored trousers that transition smoothly from corporate meetings to dinner dates.",
        "price": 1599,
        "image": "https://i.pinimg.com/736x/d4/54/31/d4543179ad19ba96ab80fb98160f472b.jpg",
        "category": "pants",
        "stock": 25,
    },
    {
        "name": "Tailored Casual Fit White",
        "description": "Clean white tailored trousers crafted from heavy linen-cotton blend for summer occasions.",
        "price": 1499,
        "image": "https://i.pinimg.com/736x/f8/eb/2e/f8eb2ec0f9f288ddcecc0f182429ea17.jpg",
        "category": "pants",
        "stock": 16,
    },
    {
        "name": "Tailored Casual Fit Cream",
        "description": "Sophisticated cream pleated trousers offering a luxurious old-money aesthetic.",
        "price": 3299,
        "image": "https://i.pinimg.com/736x/5d/ff/a0/5dffa0ca31b0ed43e5e9e1bad3cfbe9b.jpg",
        "category": "pants",
        "stock": 14,
    },
    {
        "name": "Tailored Casual Fit Brown",
        "description": "Warm earth-tone tailored trousers made with wool blend fabric for comfort and structure.",
        "price": 1349,
        "image": "https://i.pinimg.com/736x/88/cb/38/88cb381279a3784dcf6c1b35c65f401f.jpg",
        "category": "pants",
        "stock": 20,
    },
    {
        "name": "Flannel-Lined Pants",
        "description": "Cozy flannel-lined winter pants providing warmth and wind resistance without bulk.",
        "price": 1239,
        "image": "https://i.pinimg.com/736x/3e/58/91/3e5891f501ecb150b9d480d6b8ee225f.jpg",
        "category": "pants",
        "stock": 17,
    },
    {
        "name": "Korean Pants Dark Brown",
        "description": "Minimalist Korean drape wide-leg trousers featuring a fluid silhouette and clean front.",
        "price": 3239,
        "image": "https://i.pinimg.com/736x/e3/b5/bb/e3b5bb4b9f361c9d9810b42b16f74e67.jpg",
        "category": "pants",
        "stock": 12,
    },
    {
        "name": "Korean Pants Loose Fit",
        "description": "Ultra-relaxed loose-fit Korean trousers with cropped hem, great for styling with sneakers.",
        "price": 4229,
        "image": "https://i.pinimg.com/736x/d1/0c/46/d10c466e48cb6325d65e7c0837052e99.jpg",
        "category": "pants",
        "stock": 10,
    },
    {
        "name": "Korean Pants Brown",
        "description": "Versatile brown Korean trousers designed with tapered ankles and elastic back waist.",
        "price": 1429,
        "image": "https://i.pinimg.com/736x/c4/5f/20/c45f20d5e08d496518818ba30bdb3c2f.jpg",
        "category": "pants",
        "stock": 22,
    },
    {
        "name": "Korean Pants White",
        "description": "Modern minimalist white trousers offering an ultra-clean, contemporary Korean fashion look.",
        "price": 1419,
        "image": "https://i.pinimg.com/736x/4f/fc/44/4ffc44f688e661e59a26fc569a619128.jpg",
        "category": "pants",
        "stock": 19,
    },
    {
        "name": "Korean Pants Lined",
        "description": "Structured straight-cut trousers with micro-texture weave and crease-resistant fabric.",
        "price": 1442,
        "image": "https://i.pinimg.com/736x/77/63/74/776374b9f6ae85f56534d1f1442ce3b8.jpg",
        "category": "pants",
        "stock": 20,
    },
    {
        "name": "Tailored Formal Bootcut Rust",
        "description": "Eye-catching rust orange bootcut trousers tailored for runway-inspired formal occasions.",
        "price": 1659,
        "image": "https://i.pinimg.com/1200x/44/3e/95/443e95c2609312c2edc279420d087201.jpg",
        "category": "pants",
        "stock": 15,
    },
    {
        "name": "Tailored Formal Bootcut Brown",
        "description": "Rich mocha brown bootcut trousers with razor-sharp center creases and premium lining.",
        "price": 1549,
        "image": "https://i.pinimg.com/736x/e6/87/95/e68795f210d932f3dfe9ca0c4e8699f1.jpg",
        "category": "pants",
        "stock": 18,
    },
    {
        "name": "Tailored Formal Bootcut Grey",
        "description": "Charcoal grey formal bootcut trousers offering a sleek elongating silhouette.",
        "price": 1412,
        "image": "https://i.pinimg.com/736x/cd/89/0f/cd890f3f4600a422e1502190b3cd6f46.jpg",
        "category": "pants",
        "stock": 25,
    },

    # ------------------- SUNGLASSES -------------------
    {
        "name": "Frameless Black Sunglasses",
        "description": "Sleek rimless sunglasses with gradient black UV400 protective lenses and ultra-lightweight arms.",
        "price": 1199,
        "image": "https://i.pinimg.com/736x/6f/39/58/6f395823b7bc10092301881393806af5.jpg",
        "category": "sunglasses",
        "stock": 30,
    },
    {
        "name": "Frameless Transparent Sunglasses",
        "description": "Modern transparent rimless eyewear offering high-clarity lenses with 100% UV protection.",
        "price": 1299,
        "image": "https://i.pinimg.com/736x/6b/c9/7c/6bc97c68913a23b487cb75343334dcfe.jpg",
        "category": "sunglasses",
        "stock": 25,
    },
    {
        "name": "Frameless Bluecut Sunglasses",
        "description": "Dual-purpose anti-blue light and UV protective sunglasses with futuristic blue mirror tint.",
        "price": 2799,
        "image": "https://i.pinimg.com/736x/c4/95/29/c495294d6746aac55701296a22160b68.jpg",
        "category": "sunglasses",
        "stock": 15,
    },
    {
        "name": "Frameless Gold Sunglasses",
        "description": "Luxury rimless sunglasses accented with polished 18k gold-plated bridge and temple arms.",
        "price": 1499,
        "image": "https://i.pinimg.com/1200x/6c/15/2f/6c152fca53a51e0ff05a342d437a58e8.jpg",
        "category": "sunglasses",
        "stock": 20,
    },
    {
        "name": "Prada Style Rectangle Sunglasses Black",
        "description": "Geometric thick-frame rectangular sunglasses inspired by high-fashion runway trends.",
        "price": 1399,
        "image": "https://i.pinimg.com/1200x/ee/b3/f7/eeb3f76bb755b50e20eb88a306610eeb.jpg",
        "category": "sunglasses",
        "stock": 28,
    },
    {
        "name": "Wraparound Sunglasses Black",
        "description": "Aerodynamic Y2K wraparound sunglasses engineered for outdoor adventures and bold streetwear styling.",
        "price": 1399,
        "image": "https://i.pinimg.com/1200x/25/21/8f/25218fd882b06571e5b438290c52863e.jpg",
        "category": "sunglasses",
        "stock": 22,
    },
    {
        "name": "Classy Rectangular Gold",
        "description": "Timeless rectangular metal wireframe sunglasses with gold finish and dark polarized lenses.",
        "price": 1599,
        "image": "https://i.pinimg.com/1200x/26/ea/55/26ea55ce9aa91622b6e4997d6e74bf89.jpg",
        "category": "sunglasses",
        "stock": 18,
    },
    {
        "name": "Classy Rectangular Silver",
        "description": "Minimalist silver frame sunglasses featuring scratch-resistant mirrored polarized lenses.",
        "price": 1599,
        "image": "https://i.pinimg.com/1200x/eb/b8/d0/ebb8d0f24c7ac0e2b78dcda5418582b4.jpg",
        "category": "sunglasses",
        "stock": 20,
    },
    {
        "name": "LYZOIT Square Sunglasses",
        "description": "Bold square-cut sunglasses with glossy acetate finish and comfortable sculpted nose pads.",
        "price": 1499,
        "image": "https://i.pinimg.com/736x/2e/fc/b6/2efcb6924dba307821108c42b589592a.jpg",
        "category": "sunglasses",
        "stock": 16,
    },
    {
        "name": "Square Rimless Black",
        "description": "Premium square rimless glasses with beveled edge lenses and titanium bridge construction.",
        "price": 3299,
        "image": "https://i.pinimg.com/1200x/2a/51/3f/2a513f20345b70a00182d40ac1a62256.jpg",
        "category": "sunglasses",
        "stock": 12,
    },
    {
        "name": "Classy Square Sunglasses",
        "description": "Classic square silhouette with subtle tortoiseshell patterns and category 3 sun protection.",
        "price": 1349,
        "image": "https://i.pinimg.com/1200x/c5/0c/15/c50c15efc21980c30c5e0e5ec560e51a.jpg",
        "category": "sunglasses",
        "stock": 25,
    },
    {
        "name": "Essential Aviator Sunglasses",
        "description": "The quintessential teardrop aviator with double brow bar and crystal green lenses.",
        "price": 1239,
        "image": "https://i.pinimg.com/736x/0f/0d/a7/0f0da710004463f39b7620ccdb62340f.jpg",
        "category": "sunglasses",
        "stock": 35,
    },
    {
        "name": "Amber Skye Sunglasses",
        "description": "Warm amber tint lenses paired with golden aviator frame for sunset drives and city walks.",
        "price": 3239,
        "image": "https://i.pinimg.com/736x/f3/fc/02/f3fc023806a6dec81dd293659bc71c59.jpg",
        "category": "sunglasses",
        "stock": 14,
    },
    {
        "name": "Subzero Aviator Sunglasses",
        "description": "Sporty mirrored aviator sunglasses providing maximum glare reduction and high durability.",
        "price": 4229,
        "image": "https://i.pinimg.com/736x/0a/dd/49/0add49a4eac83023e9ddfe271fc41f7b.jpg",
        "category": "sunglasses",
        "stock": 10,
    },
    {
        "name": "Square Rimless Black Matte",
        "description": "Lightweight rimless black sunglasses with anti-reflective coating on inner lens surfaces.",
        "price": 1429,
        "image": "https://i.pinimg.com/736x/1a/52/c9/1a52c9cab39f997d2fd57196c002d6e1.jpg",
        "category": "sunglasses",
        "stock": 24,
    },
    {
        "name": "Square Rimless Blue",
        "description": "Gradient blue rimless lenses with featherlight temples for all-day comfort.",
        "price": 1419,
        "image": "https://i.pinimg.com/736x/3f/c8/7f/3fc87f71258110af7bdd6902a03da85b.jpg",
        "category": "sunglasses",
        "stock": 20,
    },
    {
        "name": "Ray-Ban Round Metal Black",
        "description": "Iconic round wireframe sunglasses featuring dark green G-15 glass lenses and black metal rims.",
        "price": 1442,
        "image": "https://i.pinimg.com/736x/bd/e9/ea/bde9ea7f54e63584b9305928286002bb.jpg",
        "category": "sunglasses",
        "stock": 30,
    },
    {
        "name": "Ray Metal Silver",
        "description": "Vintage round silver wireframe sunglasses loved by musicians and creators worldwide.",
        "price": 1659,
        "image": "https://i.pinimg.com/1200x/33/cd/19/33cd194b3acf9ae46dd1623e8c5fca94.jpg",
        "category": "sunglasses",
        "stock": 22,
    },
    {
        "name": "Round Metal Silver Mirror",
        "description": "High-shine silver mirrored round sunglasses with adjustable silicone nose pads.",
        "price": 1549,
        "image": "https://i.pinimg.com/1200x/0d/14/e1/0d14e15bc108ffcc3cc76c16887cd6fb.jpg",
        "category": "sunglasses",
        "stock": 18,
    },
    {
        "name": "Ray-Ban Round Metal Wood Finish",
        "description": "Limited edition round sunglasses with wood grain textured temples and brown polarized lenses.",
        "price": 1412,
        "image": "https://i.pinimg.com/736x/55/23/07/5523070dcb0b62d986b06056e3c0244d.jpg",
        "category": "sunglasses",
        "stock": 15,
    },

    # ------------------- SHOES -------------------
    {
        "name": "Classic White Leather Sneakers",
        "description": "Clean minimalist low-top sneakers in premium full-grain white leather with cushioned insoles.",
        "price": 2499,
        "image": "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 30,
    },
    {
        "name": "Suede Chelsea Boots Tan",
        "description": "Handcrafted tan suede Chelsea boots with elastic side gussets and durable crepe soles.",
        "price": 3999,
        "image": "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 18,
    },
    {
        "name": "Urban High-Top Sneakers Black",
        "description": "Streetwear high-top leather sneakers with padded collar and grippy rubber vulcanized outsoles.",
        "price": 2899,
        "image": "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 22,
    },
    {
        "name": "Formal Oxford Leather Shoes Brown",
        "description": "Sophisticated closed-lacing brown Oxford dress shoes with Goodyear welt construction.",
        "price": 3499,
        "image": "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 15,
    },
    {
        "name": "Penny Loafers Burgundy",
        "description": "Polished burgundy calfskin leather penny loafers with hand-stitched moc toe details.",
        "price": 3299,
        "image": "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 20,
    },
    {
        "name": "Retro Runner Sneakers Olive",
        "description": "Vintage running shoe silhouette combining suede overlays, breathable mesh, and EVA midsoles.",
        "price": 2699,
        "image": "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 25,
    },
    {
        "name": "Leather Derby Shoes Black",
        "description": "Versatile open-laced black leather Derby shoes designed for comfortable all-day formal wear.",
        "price": 3199,
        "image": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 18,
    },
    {
        "name": "Chukka Boots Dark Brown",
        "description": "Ankle-height dark brown leather Chukka boots with two-eyelet lacing and sturdy tread soles.",
        "price": 3799,
        "image": "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 14,
    },
    {
        "name": "Minimalist Slip-on Canvas Grey",
        "description": "Casual slip-on canvas shoes featuring elastic side accents and flexible vulcanized soles.",
        "price": 1899,
        "image": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 28,
    },
    {
        "name": "Combat Boots Matte Black",
        "description": "Heavy-duty 8-eyelet matte black leather combat boots with rugged lug soles and side zipper.",
        "price": 4499,
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 12,
    },
    {
        "name": "Monk Strap Dress Shoes Cognac",
        "description": "Double monk strap dress shoes in hand-burnished cognac leather with silver-tone buckles.",
        "price": 3899,
        "image": "https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 16,
    },
    {
        "name": "Air Cushion Sport Trainers",
        "description": "High-performance athletic trainers featuring responsive air cushioning and breathable knit uppers.",
        "price": 2999,
        "image": "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 35,
    },
    {
        "name": "Italian Tassel Loafers Navy",
        "description": "Luxurious navy blue suede loafers with leather tassels and stacked wooden heels.",
        "price": 3599,
        "image": "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 15,
    },
    {
        "name": "Vintage Canvas Low Sneakers",
        "description": "Authentic low-profile canvas skate sneakers with contrast stitching and reinforced toe cap.",
        "price": 1999,
        "image": "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 25,
    },
    {
        "name": "Streetwear Chunky Sole Sneakers",
        "description": "Architectural chunky platform trainers with sculpted multi-layered geometric soles.",
        "price": 3399,
        "image": "https://images.unsplash.com/photo-1512990414788-d97cb4a25db3?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 19,
    },
    {
        "name": "Handcrafted Brogues Walnut",
        "description": "Wingtip brogue shoes crafted in walnut leather with intricate decorative perforations.",
        "price": 4199,
        "image": "https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 10,
    },
    {
        "name": "Everyday Walking Shoes Charcoal",
        "description": "Ergonomic charcoal mesh walking shoes designed for optimal arch support and shock absorption.",
        "price": 2199,
        "image": "https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 30,
    },
    {
        "name": "Desert Suede Boots Sand",
        "description": "Classic sand suede desert boots with crepe rubber sole and minimal two-eyelet lacing.",
        "price": 3699,
        "image": "https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 16,
    },
    {
        "name": "Classic Court Tennis Shoes",
        "description": "Heritage court sneakers with perforated leather panels and green heel tab accents.",
        "price": 2599,
        "image": "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 24,
    },
    {
        "name": "Leather Chelsea Boots Black",
        "description": "Sleek black polished leather Chelsea boots with pull tab and slim dress silhouette.",
        "price": 4299,
        "image": "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&auto=format&fit=crop&q=80",
        "category": "shoes",
        "stock": 14,
    },
    # ------------------- WALLETS -------------------
    {
        "name": "Classic Bi-Fold Leather Wallet Brown",
        "description": "Handcrafted from full-grain genuine leather with 8 card slots, dual cash compartment, and RFID protection.",
        "price": 1499,
        "image": "https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80",
        "category": "wallets",
        "stock": 30,
    },
    {
        "name": "Slim RFID Minimalist Cardholder Black",
        "description": "Ultra-slim front-pocket card case featuring aerospace-grade RFID blocking technology and quick-draw card slot.",
        "price": 999,
        "image": "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80",
        "category": "wallets",
        "stock": 45,
    },
    {
        "name": "Vintage Full-Grain Bifold Tan",
        "description": "Rich tan leather wallet that develops a handsome natural patina over time. Includes ID window and billfold divider.",
        "price": 1799,
        "image": "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&auto=format&fit=crop&q=80",
        "category": "wallets",
        "stock": 25,
    },
    {
        "name": "Carbon Fiber Tactical Wallet",
        "description": "Modern lightweight carbon fiber card case with integrated spring steel money clip and elastic expansion band.",
        "price": 1299,
        "image": "https://images.unsplash.com/photo-1554412933-514a83d2f3c8?w=800&auto=format&fit=crop&q=80",
        "category": "wallets",
        "stock": 35,
    },
    {
        "name": "Textured Saffiano Leather Wallet Navy",
        "description": "Scratch-resistant cross-grain Saffiano leather wallet in deep navy with embossed silver foil NOVA emblem.",
        "price": 1899,
        "image": "https://images.unsplash.com/photo-1563903530-0879fe6596e0?w=800&auto=format&fit=crop&q=80",
        "category": "wallets",
        "stock": 20,
    },
    {
        "name": "Zip-Around Travel Organizer Wallet",
        "description": "Secure wrap-around zippered wallet designed to hold passport, currency, coins, boarding passes, and up to 12 cards.",
        "price": 2199,
        "image": "https://images.unsplash.com/photo-1614026480418-bd11fdb9fa06?w=800&auto=format&fit=crop&q=80",
        "category": "wallets",
        "stock": 18,
    },
    {
        "name": "Slimline Money Clip Leather Wallet",
        "description": "Ultra-compact profile with built-in magnetic brass money clip and 6 precision-cut card sleeves.",
        "price": 1199,
        "image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80",
        "category": "wallets",
        "stock": 40,
    },
    {
        "name": "Distressed Hunter Leather Bi-Fold",
        "description": "Rugged oiled pull-up leather wallet built with heavy-duty contrast stitching and reinforced corners.",
        "price": 1599,
        "image": "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80",
        "category": "wallets",
        "stock": 22,
    },
    {
        "name": "Italian Pebbled Leather Wallet Cognac",
        "description": "Supple Italian pebbled calfskin wallet offering exceptional soft-touch luxury, 10 card slots, and hidden slip pockets.",
        "price": 1999,
        "image": "https://images.unsplash.com/photo-1546938576-6e6a64f317cc?w=800&auto=format&fit=crop&q=80",
        "category": "wallets",
        "stock": 15,
    },
    {
        "name": "Compact Tri-Fold Nappa Wallet",
        "description": "Space-efficient three-fold construction made with butter-soft Nappa leather and smooth cloth lining.",
        "price": 1499,
        "image": "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&auto=format&fit=crop&q=80",
        "category": "wallets",
        "stock": 28,
    },
    # ------------------- WATCHES -------------------
    {
        "name": "Minimalist Chronograph Leather Watch Black",
        "description": "Sleek 42mm matte black casing with dual sub-dials, sapphire crystal glass, and Italian calfskin leather band.",
        "price": 4999,
        "image": "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80",
        "category": "watches",
        "stock": 20,
    },
    {
        "name": "Classic Automatic Stainless Steel Watch Silver",
        "description": "Self-winding mechanical movement with 40-hour power reserve, brushed stainless steel bracelet, and exhibition caseback.",
        "price": 6499,
        "image": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80",
        "category": "watches",
        "stock": 15,
    },
    {
        "name": "Rose Gold Heritage Mesh Watch",
        "description": "Refined 40mm rose gold plated case paired with a breathable Milanese stainless steel mesh strap and date window.",
        "price": 5299,
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
        "category": "watches",
        "stock": 18,
    },
    {
        "name": "Aviator Military Field Watch Olive",
        "description": "Luminescent hands and numerals, rugged stainless steel casing, and high-durability woven nylon NATO strap.",
        "price": 3999,
        "image": "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=800&auto=format&fit=crop&q=80",
        "category": "watches",
        "stock": 25,
    },
    {
        "name": "Ocean Diver 200M Automatic Blue",
        "description": "Professional 200-meter water resistance diver's watch with unidirectional ceramic bezel and deep sunburst blue dial.",
        "price": 7999,
        "image": "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80",
        "category": "watches",
        "stock": 12,
    },
    {
        "name": "Skeleton Mechanical Dial Leather Watch",
        "description": "Intricate open-worked skeleton dial exposing precise gear escapements, encased in polished gunmetal with tan leather strap.",
        "price": 6999,
        "image": "https://images.unsplash.com/photo-1547996160-71dfa63096aa?w=800&auto=format&fit=crop&q=80",
        "category": "watches",
        "stock": 10,
    },
    {
        "name": "Vintage Dress Watch Gold & Brown Leather",
        "description": "Art-deco inspired Roman numerals, warm gold-plated case, and hand-stitched crocodile-embossed brown leather band.",
        "price": 5799,
        "image": "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&auto=format&fit=crop&q=80",
        "category": "watches",
        "stock": 16,
    },
    {
        "name": "Sunray Blue Dial Steel Bracelet Watch",
        "description": "Striking sunburst blue dial with polished hour batons, magnified date display, and solid link oyster steel bracelet.",
        "price": 5999,
        "image": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80",
        "category": "watches",
        "stock": 22,
    },
    {
        "name": "Modern Minimal Silver & Navy Watch",
        "description": "Ultra-clean Bauhaus aesthetic with slim brushed silver casing, dark navy sunray face, and quick-release genuine leather strap.",
        "price": 4199,
        "image": "https://images.unsplash.com/photo-1517463767756-32d80d210515?w=800&auto=format&fit=crop&q=80",
        "category": "watches",
        "stock": 24,
    },
    {
        "name": "Luxury Quartz Slim Dress Watch Gunmetal",
        "description": "6.8mm ultra-thin case profile engineered from 316L surgical-grade steel in gunmetal finish with sapphire crystal glass.",
        "price": 4799,
        "image": "https://images.unsplash.com/photo-1518131672697-613becd4fab5?w=800&auto=format&fit=crop&q=80",
        "category": "watches",
        "stock": 19,
    },
]


class Command(BaseCommand):
    help = "Seeds database with all products for shirts, pants, sunglasses, and shoes"

    def handle(self, *args, **options):
        self.stdout.write("Seeding products into database...")
        
        # Clear existing products to ensure fresh, clean data
        deleted_count, _ = Product.objects.all().delete()
        self.stdout.write(f"Cleared {deleted_count} previous products.")

        created_count = 0
        for item in PRODUCTS_DATA:
            Product.objects.create(
                name=item["name"],
                description=item["description"],
                price=item["price"],
                image=item["image"],
                category=item["category"],
                stock=item.get("stock", 10),
            )
            created_count += 1

        self.stdout.write(self.style.SUCCESS(f"Successfully seeded {created_count} products across all categories!"))
